In [24]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import torch
from torch_geometric.data import InMemoryDataset, Data

In [2]:
df = pd.read_csv("yoochoose-clicks.dat")

/home/pranjal/miniconda3/envs/gcn/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [5]:
df.columns = ["session_id", "timestamp", "item_id", "category"]

In [9]:
grouped = df.groupby("session_id")

In [48]:
data_list = []
count = 0
for session_id, group in grouped:
    sess_item_id = LabelEncoder().fit_transform(group.item_id)
    group = group.reset_index(drop=True)
    group["sess_item_id"] = sess_item_id
    group["label"] = False
    node_features = (
        group.loc[group.session_id == session_id, ["sess_item_id", "item_id"]]
        .sort_values("sess_item_id")
        .item_id.drop_duplicates()
        .values
    )
    node_features = torch.LongTensor(node_features).unsqueeze(1)
    target_nodes = group.sess_item_id.values[1:]
    source_nodes = group.sess_item_id.values[:-1]

    edge_index = torch.tensor([source_nodes, target_nodes], dtype=torch.long)
    x = node_features

    y = torch.FloatTensor([group.label.values[0]])

    data = Data(x=x, edge_index=edge_index, y=y)
    data_list.append(data)
    count+=1
    if count ==2:
        break

In [53]:
group.loc[group.session_id == session_id, ["sess_item_id", "item_id"]]\
        .sort_values("sess_item_id")\
        .item_id.drop_duplicates()\
        .values

array([214551617, 214662742, 214757390, 214757407, 214825110])

In [54]:
edge_index

tensor([[1, 1, 4, 2, 3],
        [1, 4, 2, 3, 0]])

In [55]:
y

tensor([0.])

In [47]:
data_list[1].x,data_list[1].edge_index

(tensor([[214551617],
         [214662742],
         [214757390],
         [214757407],
         [214825110]]),
 tensor([[1, 1, 4, 2, 3],
         [1, 4, 2, 3, 0]]))

In [46]:
data_list

[Data(edge_index=[2, 2], x=[3, 1], y=[1]),
 Data(edge_index=[2, 5], x=[5, 1], y=[1]),
 Data(edge_index=[2, 2], x=[3, 1], y=[1]),
 Data(edge_index=[2, 1], x=[2, 1], y=[1]),
 Data(edge_index=[2, 1], x=[2, 1], y=[1]),
 Data(edge_index=[2, 1], x=[2, 1], y=[1]),
 Data(edge_index=[2, 1], x=[1, 1], y=[1]),
 Data(edge_index=[2, 2], x=[1, 1], y=[1]),
 Data(edge_index=[2, 11], x=[9, 1], y=[1]),
 Data(edge_index=[2, 1], x=[1, 1], y=[1]),
 Data(edge_index=[2, 2], x=[2, 1], y=[1]),
 Data(edge_index=[2, 2], x=[2, 1], y=[1]),
 Data(edge_index=[2, 2], x=[1, 1], y=[1]),
 Data(edge_index=[2, 1], x=[2, 1], y=[1]),
 Data(edge_index=[2, 1], x=[1, 1], y=[1]),
 Data(edge_index=[2, 3], x=[2, 1], y=[1]),
 Data(edge_index=[2, 5], x=[2, 1], y=[1]),
 Data(edge_index=[2, 15], x=[11, 1], y=[1]),
 Data(edge_index=[2, 3], x=[1, 1], y=[1]),
 Data(edge_index=[2, 3], x=[2, 1], y=[1]),
 Data(edge_index=[2, 3], x=[4, 1], y=[1]),
 Data(edge_index=[2, 9], x=[9, 1], y=[1]),
 Data(edge_index=[2, 2], x=[2, 1], y=[1]),
 Data(ed